// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV5HwBcHfHd26wDwowrHpFxyhvhH30WRQ',
    appId: '1:976827215471:web:d64a6fc00bf270f86d679a',
    messagingSenderId: '976827215471',
    projectId: 'mini-project-flutter-9d0ba',
    authDomain: 'mini-project-flutter-9d0ba.firebaseapp.com',
    storageBucket: 'mini-project-flutter-9d0ba.appspot.com',
    measurementId: 'G-79P36KXSYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqvtD1AP0WiWwxMEOdVn41Xb7Gpqhhq7A',
    appId: '1:976827215471:android:b9009fcaca2c2eea6d679a',
    messagingSenderId: '976827215471',
    projectId: 'mini-project-flutter-9d0ba',
    storageBucket: 'mini-project-flutter-9d0ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjolEYeFpPgoqgStG22Vc45Va71BUR1bI',
    appId: '1:976827215471:ios:9673cf5a159528bd6d679a',
    messagingSenderId: '976827215471',
    projectId: 'mini-project-flutter-9d0ba',
    storageBucket: 'mini-project-flutter-9d0ba.appspot.com',
    iosBundleId: 'com.example.todo',
  );
}
