// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5qMJp2uaPTsh7Xd_cNjibCEiO1kX-ano',
    appId: '1:630465664342:web:625a70c8e521fb56e032f7',
    messagingSenderId: '630465664342',
    projectId: 'todo-app-mini-project',
    authDomain: 'todo-app-mini-project.firebaseapp.com',
    storageBucket: 'todo-app-mini-project.appspot.com',
    measurementId: 'G-QRY6N95J66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxkvePSaKkym9Z4MebSYaHxv7fctbJv68',
    appId: '1:630465664342:android:b4f4d41729e49942e032f7',
    messagingSenderId: '630465664342',
    projectId: 'todo-app-mini-project',
    storageBucket: 'todo-app-mini-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz1geRH8Wz1il7dlaQIKfnc3UsfqRkDFU',
    appId: '1:630465664342:ios:137ef35e541afbaee032f7',
    messagingSenderId: '630465664342',
    projectId: 'todo-app-mini-project',
    storageBucket: 'todo-app-mini-project.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );
}
